/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-vertical per-month URLs to deployed dashboards and published GDocs.
 */
export interface ArtifactLinks {
  schema_version: string;
  payload_type: "artifact_links";
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  artifacts: ArtifactLink[];
}
export interface ArtifactLink {
  artifact_id: string;
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  month: number;
  type: "dashboard" | "report" | "gdoc" | "gdrive" | "presentation";
  url: string;
  title: string;
}
