/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-vertical cascade viewer data, keyed by question_id. Map keys follow the stable identity model: {vertical}_{snapshot}_{Q_NNN}. Consumers look up cascades by question_id from executive_questions.
 */
export interface CascadeData {
  schema_version: string;
  payload_type: "cascade_data";
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  /**
   * Map from question_id to CascadeEntry. Keys follow stable identity model.
   */
  cascades: {
    [k: string]: CascadeEntry;
  };
}
export interface CascadeEntry {
  question_id: string;
  reported_value: string;
  audited_value: string;
  /**
   * Human-readable delta (e.g., '+23%', '-$1.2M')
   */
  delta: string;
  root_cause: string;
  consequence: string;
  reviewer_badge: ReviewerBadge;
  /**
   * @minItems 1
   * @maxItems 6
   */
  timeline_steps:
    | [TimelineStep]
    | [TimelineStep, TimelineStep]
    | [TimelineStep, TimelineStep, TimelineStep]
    | [TimelineStep, TimelineStep, TimelineStep, TimelineStep]
    | [TimelineStep, TimelineStep, TimelineStep, TimelineStep, TimelineStep]
    | [TimelineStep, TimelineStep, TimelineStep, TimelineStep, TimelineStep, TimelineStep];
}
export interface ReviewerBadge {
  reviewer_name: string;
  status: "pending" | "approved" | "rejected";
}
export interface TimelineStep {
  step_type: "finding" | "correction" | "dashboard" | "report" | "presentation" | "governance";
  label: string;
  /**
   * References screenshot_manifest or artifact_links. Null if step has no artifact.
   */
  artifact_id?: string;
  description?: string;
}
