/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-vertical discover panel insight cards, question-framed and linked to dashboard views.
 */
export interface DiscoverInsights {
  schema_version: string;
  payload_type: "discover_insights";
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  /**
   * @minItems 1
   * @maxItems 10
   */
  insights:
    | [DiscoverInsight]
    | [DiscoverInsight, DiscoverInsight]
    | [DiscoverInsight, DiscoverInsight, DiscoverInsight]
    | [DiscoverInsight, DiscoverInsight, DiscoverInsight, DiscoverInsight]
    | [DiscoverInsight, DiscoverInsight, DiscoverInsight, DiscoverInsight, DiscoverInsight]
    | [DiscoverInsight, DiscoverInsight, DiscoverInsight, DiscoverInsight, DiscoverInsight, DiscoverInsight]
    | [
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight
      ]
    | [
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight
      ]
    | [
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight
      ]
    | [
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight,
        DiscoverInsight
      ];
}
export interface DiscoverInsight {
  /**
   * Stable ID: {vertical}_{INS_NNN}
   */
  insight_id: string;
  question_text: string;
  dashboard_link: string;
  /**
   * @minItems 1
   */
  finding_ids: [string, ...string[]];
}
