/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-vertical executive questions with answer summaries for question buttons and cascade entry points.
 */
export interface ExecutiveQuestions {
  schema_version: string;
  payload_type: "executive_questions";
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  /**
   * @minItems 1
   * @maxItems 10
   */
  questions:
    | [ExecutiveQuestion]
    | [ExecutiveQuestion, ExecutiveQuestion]
    | [ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion]
    | [ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion]
    | [ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion]
    | [ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion, ExecutiveQuestion]
    | [
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion
      ]
    | [
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion
      ]
    | [
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion
      ]
    | [
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion,
        ExecutiveQuestion
      ];
}
export interface ExecutiveQuestion {
  /**
   * Stable ID: {vertical}_{snapshot}_{Q_NNN}
   */
  question_id: string;
  priority: "flagship" | "secondary";
  question_text: string;
  answer_summary: string;
  severity: "critical" | "high" | "medium" | "low";
}
