/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-vertical selector card content: headline discrepancy, consequence, trust cue, and score.
 */
export interface HookMetrics {
  schema_version: string;
  payload_type: "hook_metrics";
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  /**
   * One-line hook: the core data problem (e.g., '7 broken metrics across 3 dashboards')
   */
  discrepancy_headline: string;
  /**
   * Business consequence in plain language
   */
  consequence: string;
  /**
   * Trust signal (e.g., 'Reviewed by Jane Smith, VP Analytics')
   */
  trust_cue: string;
  /**
   * Current audit score for this vertical
   */
  score: number;
  /**
   * Visual urgency level for selector card rendering
   */
  severity_level: "critical" | "warning" | "moderate" | "healthy";
}
