/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-vertical per-month dashboard and report preview images.
 */
export interface ScreenshotManifest {
  schema_version: string;
  payload_type: "screenshot_manifest";
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  screenshots: ScreenshotEntry[];
}
export interface ScreenshotEntry {
  /**
   * Stable ID: {vertical}_{month}_{type}_{NNN}
   */
  artifact_id: string;
  vertical: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  month: number;
  type: "dashboard" | "report";
  url: string;
  alt_text: string;
}
