/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-vertical commercial copy source: status quo vs BayesIQ comparison, headline finding, and CTA configuration.
 */
export interface VerticalNarrative {
  schema_version: string;
  payload_type: "vertical_narrative";
  vertical_id: "hospital" | "real_estate" | "saas" | "retail" | "fintech";
  /**
   * Human-readable vertical name (e.g., 'Hospital', 'Real Estate')
   */
  display_name: string;
  /**
   * What happens without BayesIQ — specific, not generic
   */
  status_quo: string;
  /**
   * What changes with BayesIQ — specific, grounded in data
   */
  with_bayesiq: string;
  /**
   * Most devastating finding, one sentence
   */
  headline_finding: string;
  /**
   * Primary CTA button text for this vertical (e.g., 'Book a Hospital Data Diagnostic')
   */
  cta_label: string;
  /**
   * CTA type for rendering logic
   */
  cta_variant: "diagnostic" | "reliability_program" | "book_session";
}
