/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { Reviewer } from "./common";

/**
 * Per-finding/feedback approval status with inline reviewer attribution. Aligned with platform PR #316 contract_c.approval_metadata_v1 schema.
 */
export interface ApprovalMetadata {
  schema_version: 1;
  payload_type: "contract_c.approval_metadata";
  /**
   * UTC ISO 8601 timestamp of export generation
   */
  generated_at: string;
  items: ApprovalItem[];
}
export interface ApprovalItem {
  /**
   * What kind of object this approval covers
   */
  object_type: "finding" | "feedback" | "approval";
  /**
   * ID of the finding, feedback, or approval being approved. References Contract B cascade_data for findings.
   */
  object_id: string;
  approval_status: "pending" | "approved" | "rejected" | "deferred";
  /**
   * Whether this record was seeded for demo, approved during demo, or from live production
   */
  record_origin: "demo_seeded" | "demo_approved" | "live";
  /**
   * Platform-internal approval record ID for traceability
   */
  source_approval_id: string;
  reviewer: Reviewer;
  /**
   * UTC ISO 8601 timestamp of the approval action
   */
  timestamp: string;
  /**
   * Optional reviewer note, max 500 chars
   */
  review_note?: string | null;
}
