/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-finding approval status for trust micro-badges.
 */
export interface ApprovalStatus {
  schema_version: string;
  payload_type: "approval_status";
  approvals: ApprovalRecord[];
}
export interface ApprovalRecord {
  /**
   * References a finding in Contract B cascade_data
   */
  finding_id: string;
  status: "pending" | "approved" | "rejected";
  /**
   * Null/absent if status is pending
   */
  approved_at?: string;
  /**
   * References reviewer_attribution
   */
  reviewer_id: string;
}
