/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Business event governance state: metric redefinitions, restatements, corrections with preview vs approved status.
 */
export interface BusinessEvents {
  schema_version: string;
  payload_type: "business_events";
  events: BusinessEvent[];
}
export interface BusinessEvent {
  event_id: string;
  finding_id: string;
  event_type: "metric_redefinition" | "restatement" | "correction";
  state: "preview" | "approved";
  description: string;
}
