/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { Reviewer } from "./common";

/**
 * Per-question governance overlay for cascade viewer. Aligned with platform contract_c.cascade_governance_v1 (PR #329).
 */
export interface CascadeGovernance {
  schema_version: 1;
  payload_type: "contract_c.cascade_governance";
  generated_at: string;
  items: CascadeGovernanceItem[];
}
export interface CascadeGovernanceItem {
  question_id: string;
  approval_status: "pending" | "approved" | "rejected" | "deferred";
  record_origin: "demo_seeded" | "demo_approved" | "live";
  reviewer: Reviewer;
  review_note?: string | null;
  finding_ids: string[];
  feedback_ids: string[];
  event_ids: string[];
  ts_requested: string;
  ts_resolved: string;
}
