/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-finding feedback conversation chains: comment → review → resolution.
 */
export interface FeedbackThreads {
  schema_version: string;
  payload_type: "feedback_threads";
  threads: FeedbackThread[];
}
export interface FeedbackThread {
  thread_id: string;
  /**
   * References Contract B cascade_data finding
   */
  finding_id: string;
  /**
   * @minItems 1
   */
  comments: [ThreadComment, ...ThreadComment[]];
}
export interface ThreadComment {
  author: string;
  body: string;
  timestamp: string;
  type: "comment" | "review" | "resolution";
}
