/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GDoc/GDrive URLs for published governance documents.
 */
export interface PublishedDocs {
  schema_version: string;
  payload_type: "published_docs";
  docs: PublishedDoc[];
}
export interface PublishedDoc {
  doc_id: string;
  finding_id: string;
  url: string;
  title: string;
  type: "gdoc" | "gdrive" | "dashboard";
}
