/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Reviewer identity records: name, role, organization.
 */
export interface ReviewerAttribution {
  schema_version: string;
  payload_type: "reviewer_attribution";
  reviewers: ReviewerRecord[];
}
export interface ReviewerRecord {
  reviewer_id: string;
  name: string;
  role: string;
  organization?: string;
}
