/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Typed review context blocks per governance object. Aligned with platform contract_c.review_context_v1 (PR #325).
 */
export interface ReviewContext {
  schema_version: 1;
  payload_type: "contract_c.review_context";
  generated_at: string;
  items: ReviewContextItem[];
}
export interface ReviewContextItem {
  object_type: string;
  object_id: string;
  source_approval_id: string;
  timestamp: string;
  review_context: ReviewContextBlock[];
}
export interface ReviewContextBlock {
  type:
    | "summary_stat"
    | "finding_list"
    | "assumption_list"
    | "candidate_list"
    | "warning"
    | "artifact_link_group";
  [k: string]: unknown;
}
