/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pre-compiled trust badge data for rendering on selector cards, cascades, and previews.
 */
export interface TrustBadges {
  schema_version: string;
  payload_type: "trust_badges";
  badges: TrustBadge[];
}
export interface TrustBadge {
  finding_id: string;
  badge_type: "audit_verified" | "governance_approved" | "stakeholder_reviewed";
  reviewer_name: string;
  status: "pending" | "approved" | "rejected";
  verified_at?: string;
}
