import type { Metadata } from "next";
import CaseStudyCard from "@/components/CaseStudyCard";
import CTA from "@/components/CTA";

export const metadata: Metadata = {
  title: "Case Studies",
  description:
    "Examples of how BayesIQ finds and fixes hidden data quality issues.",
  openGraph: {
    title: "Case Studies — BayesIQ",
    description:
      "Examples of how BayesIQ finds and fixes hidden data quality issues.",
  },
};

const caseStudies = [
  {
    industry: "Fintech",
    title: "Event Tracking Gap",
    problem:
      "Payment events missing from analytics. Revenue metrics were underreporting by approximately 12%, creating a persistent gap between analytics and finance numbers.",
    found:
      "3 event types not firing on mobile web due to a race condition in the SDK initialization. 2 required fields consistently null on iOS because of a permission change in a recent OS update.",
    fix: "Updated event instrumentation to defer until SDK ready. Added field validation tests to CI pipeline to catch null fields before deployment.",
    result:
      "Revenue metric accuracy restored. Discrepancy between analytics and finance eliminated. Validation tests now prevent regression.",
  },
  {
    industry: "Healthcare",
    title: "Metric Double-Counting",
    problem:
      "Patient engagement metric appeared inflated, driving incorrect resource allocation across departments. Leadership was making staffing decisions based on the wrong numbers.",
    found:
      "Duplicate events generated by retry logic in the mobile app. The ingestion pipeline had no deduplication, so every retry created a new record.",
    fix: "Added idempotency keys to event payloads. Implemented deduplication at the ingestion layer using a 5-minute window.",
    result:
      "Metric corrected downward by 34%. Resource allocation re-prioritized based on accurate engagement data.",
  },
  {
    industry: "E-commerce",
    title: "A/B Test Bias",
    problem:
      "A/B test results were consistently inconsistent with actual revenue data. Winning variants in tests didn't translate to real performance improvements.",
    found:
      "Assignment event was firing after page load, not before render. Fast bouncers were systematically excluded from the control group, biasing every test.",
    fix: "Moved assignment to server-side, before render. Added a validation check that compares test population sizes against expected traffic.",
    result:
      "Test framework now matches revenue data within 2% tolerance. Three previously 'winning' variants were re-evaluated — two were actually neutral.",
  },
];

export default function CaseStudiesPage() {
  return (
    <>
      <section className="px-6 py-24">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-4xl font-bold tracking-tight text-bayesiq-900">
            Case Studies
          </h1>
          <p className="mt-4 text-lg text-bayesiq-600">
            Real patterns from real data systems. These illustrate the kinds of
            issues BayesIQ finds — the ones that silently compromise your
            analytics.
          </p>
          <p className="mt-2 text-sm text-bayesiq-400">
            Based on common engagement patterns. Details anonymized.
          </p>
        </div>
      </section>

      <section className="px-6 pb-20">
        <div className="mx-auto max-w-3xl space-y-8">
          {caseStudies.map((cs) => (
            <CaseStudyCard key={cs.title} {...cs} />
          ))}
        </div>
      </section>

      <CTA
        headline="What would an audit find in your data?"
        description="Every data system has hidden issues. The question is whether you find them before or after they affect decisions."
      />
    </>
  );
}
